name: Publish to Chromatic
    uses: chromaui/action@v1
    # Chromatic GitHub Action options
    with:
        # 👇 Chromatic projectToken, refer to the manage page to obtain it.
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

        # Still need to add the following:
        # TODO: Followup with implementing the pull request workflow
